// Generated by CoffeeScript 1.6.2
(function() {
  var $, defaults, div, emulateTransitionEnd, eventNames, getVendorPropertyName, n, transformProperty, transformTypes, transformTypesDeg, transformTypesPx, unit, vendorNames, _base,
    __slice = [].slice,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  $ = jQuery;

  $.gfx = {};

  $.gfx.fn = {};

  $.fn.gfx = function() {
    var args, method;

    method = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    return $.gfx.fn[method].apply(this, args);
  };

  div = document.createElement('div');

  getVendorPropertyName = function(prop) {
    var camelProp, prefix, prefixes, vendorProp, _i, _len;

    if (prop in div.style) {
      return prop;
    }
    prefixes = ['Moz', 'Webkit', 'O', 'ms'];
    camelProp = prop.charAt(0).toUpperCase() + prop.substr(1);
    if (prop in div.style) {
      return prop;
    }
    for (_i = 0, _len = prefixes.length; _i < _len; _i++) {
      prefix = prefixes[_i];
      vendorProp = prefix + camelProp;
      if (vendorProp in div.style) {
        return vendorProp;
      }
    }
  };

  eventNames = {
    'transition': 'transitionEnd',
    'MozTransition': 'transitionend',
    'OTransition': 'oTransitionEnd',
    'WebkitTransition': 'webkitTransitionEnd',
    'msTransition': 'MSTransitionEnd'
  };

  vendorNames = n = {
    transition: getVendorPropertyName('transition'),
    transform: getVendorPropertyName('transform'),
    transformOrigin: getVendorPropertyName('transformOrigin'),
    transitionEnd: eventNames[getVendorPropertyName('transition')],
    supported: !!getVendorPropertyName('transition')
  };

  (_base = $.support).transition || (_base.transition = vendorNames.supported);

  defaults = {
    duration: 400,
    queue: true,
    easing: '',
    enabled: $.support.transition,
    properties: 'all'
  };

  transformTypes = ['scale', 'scaleX', 'scaleY', 'scale3d', 'rotate', 'rotateX', 'rotateY', 'rotateZ', 'rotate3d', 'translate', 'translateX', 'translateY', 'translateZ', 'translate3d', 'skew', 'skewX', 'skewY', 'matrix', 'matrix3d', 'perspective'];

  transformTypesPx = ['translate', 'translateX', 'translateY', 'translateZ', 'translate3d'];

  transformTypesDeg = ['rotate', 'rotateX', 'rotateY'];

  unit = function(i, units) {
    if (typeof i === 'string' && !i.match(/^[\-0-9\.]+$/)) {
      return i;
    } else {
      return '' + i + units;
    }
  };

  transformProperty = function(key, values) {
    var i, value, _i, _len;

    values = $.makeArray(values);
    for (i = _i = 0, _len = values.length; _i < _len; i = ++_i) {
      value = values[i];
      if (__indexOf.call(transformTypesPx, key) >= 0) {
        values[i] = unit(value, 'px');
      } else if (__indexOf.call(transformTypesDeg, key) >= 0) {
        values[i] = unit(value, 'deg');
      }
    }
    return values.join(',');
  };

  emulateTransitionEnd = function(duration) {
    var callback, called,
      _this = this;

    called = false;
    $(this).one(n.transitionEnd, function() {
      return called = true;
    });
    callback = function() {
      if (!called) {
        return $(_this).trigger(n.transitionEnd);
      }
    };
    return setTimeout(callback, duration);
  };

  $.gfx.fn.redraw = function() {
    return this.each(function() {
      return this.offsetHeight;
    });
  };

  $.gfx.fn.queueNext = function(callback, type) {
    if (type == null) {
      type = 'fx';
    }
    return this.queue(function() {
      callback.apply(this, arguments);
      $(this).gfx('redraw');
      return jQuery.dequeue(this, type);
    });
  };

  $.gfx.fn.transform = function(properties, options) {
    var key, transforms, value;

    options = $.extend({}, defaults, options);
    if (!options.enabled) {
      return this;
    }
    transforms = [];
    for (key in properties) {
      value = properties[key];
      if (!(__indexOf.call(transformTypes, key) >= 0)) {
        continue;
      }
      value = transformProperty(key, value);
      transforms.push("" + key + "(" + value + ")");
      delete properties[key];
    }
    if (transforms.length) {
      properties[n.transform] = transforms.join(' ');
    }
    if (options.origin) {
      properties[n.transformOrigin] = options.origin;
    }
    return this.css(properties);
  };

  $.gfx.fn.animate = function(properties, options) {
    var callback;

    options = $.extend({}, defaults, options);
    properties[n.transition] = [options.properties, unit(options.duration, 'ms'), options.easing].join(' ');
    callback = function() {
      var _ref;

      $(this).css(n.transition, '');
      if ((_ref = options.complete) != null) {
        _ref.apply(this, arguments);
      }
      if (options.queue) {
        return $(this).dequeue();
      }
    };
    return this[options.queue === false ? 'each' : 'queue'](function() {
      if (options.enabled) {
        $(this).one(n.transitionEnd, callback);
        $(this).gfx('transform', properties);
        return emulateTransitionEnd.call(this, options.duration + 50);
      } else {
        $(this).gfx('transform', properties);
        return callback();
      }
    });
  };

}).call(this);
