// Generated by CoffeeScript 1.6.2
(function() {
  var $, create;

  create = Object.create || function(o) {
    var F;

    F = function() {};
    F.prototype = o;
    return new F();
  };

  $ = jQuery;

  $ = create($);

  if (!$.gfx) {
    throw new Error('GFX required');
  }

  $.fn.animate = $.gfx.fn.animate;

  $.fn.transform = $.gfx.fn.transform;

  $.fn.queueNext = $.gfx.fn.queueNext;

  $.gfx.BOUNCING = 'cubic-bezier(.41,1.34,.51,1.01)';

  $.gfx.HARD_BOUNCING = 'cubic-bezier(.35,1.83,.62,1)';

  $.gfx.fn.popIn = function(options) {
    var _ref;

    if (options == null) {
      options = {};
    }
    if ((_ref = options.scale) == null) {
      options.scale = '.2';
    }
    $(this).queueNext(function() {
      return $(this).transform({
        origin: '50% 50%',
        scale: options.scale
      }).show();
    });
    return $(this).animate({
      scale: '1',
      opacity: '1'
    }, options);
  };

  $.gfx.fn.popOut = function(options) {
    $(this).queueNext(function() {
      return $(this).transform({
        '-webkit-transform-origin': '50% 50%',
        '-moz-transform-origin': '50% 50%',
        scale: '1',
        opacity: '1'
      });
    });
    $(this).animate({
      scale: '.2',
      opacity: '0'
    }, options);
    return $(this).queueNext(function() {
      return $(this).hide().transform({
        opacity: '1',
        scale: '1'
      });
    });
  };

  $.gfx.fn.fadeIn = function(options) {
    var _ref;

    if (options == null) {
      options = {};
    }
    if ((_ref = options.duration) == null) {
      options.duration = 1000;
    }
    $(this).queueNext(function() {
      return $(this).css({
        opacity: '0'
      }).show();
    });
    return $(this).animate({
      opacity: 1
    }, options);
  };

  $.gfx.fn.fadeOut = function(options) {
    if (options == null) {
      options = {};
    }
    $(this).queueNext(function() {
      return $(this).css({
        opacity: 1
      });
    });
    $(this).animate({
      opacity: 0
    }, options);
    return $(this).queueNext(function() {
      return $(this).hide().css({
        opacity: 1
      });
    });
  };

  $.gfx.fn.shake = function(options) {
    var distance, _ref, _ref1;

    if (options == null) {
      options = {};
    }
    if ((_ref = options.duration) == null) {
      options.duration = 100;
    }
    if ((_ref1 = options.easing) == null) {
      options.easing = 'ease-out';
    }
    distance = options.distance || 20;
    $(this).animate({
      translateX: -distance
    }, options);
    $(this).animate({
      translateX: distance
    }, options);
    $(this).animate({
      translateX: -distance
    }, options);
    $(this).animate({
      translateX: distance
    }, options);
    return $(this).queueNext(function() {
      return $(this).transform({
        translateX: 0
      });
    });
  };

  $.gfx.fn.blip = function(options) {
    if (options == null) {
      options = {};
    }
    options.scale || (options.scale = '1.15');
    $(this).animate({
      scale: options.scale
    }, options);
    return $(this).animate({
      scale: '1'
    }, options);
  };

  $.gfx.fn.explodeIn = function(options) {
    if (options == null) {
      options = {};
    }
    options.scale || (options.scale = '3');
    $(this).queueNext(function() {
      return $(this).transform({
        scale: options.scale,
        opacity: '0'
      }).show();
    });
    return $(this).animate({
      scale: '1',
      opacity: '1'
    }, options);
  };

  $.gfx.fn.explodeOut = function(options) {
    if (options == null) {
      options = {};
    }
    options.scale || (options.scale = '3');
    $(this).queueNext(function() {
      return $(this).transform({
        scale: '1',
        opacity: '1'
      });
    });
    $(this).animate({
      scale: options.scale,
      opacity: '0'
    }, options);
    if (options.reset !== false) {
      $(this).queueNext(function() {
        return $(this).hide().transform({
          scale: '1',
          opacity: '1'
        });
      });
    }
    return this;
  };

  $.gfx.fn.flipIn = function(options) {
    if (options == null) {
      options = {};
    }
    $(this).queueNext(function() {
      return $(this).transform({
        rotateY: '180deg',
        scale: '.8',
        display: 'block'
      });
    });
    return $(this).animate({
      rotateY: 0,
      scale: 1
    }, options);
  };

  $.gfx.fn.flipOut = function(options) {
    if (options == null) {
      options = {};
    }
    $(this).queueNext(function() {
      return $(this).transform({
        rotateY: 0,
        scale: 1
      });
    });
    $(this).animate({
      rotateY: '-180deg',
      scale: '.8'
    }, options);
    if (options.reset !== false) {
      $(this).queueNext(function() {
        return $(this).transform({
          scale: 1,
          rotateY: 0,
          display: 'none'
        });
      });
    }
    return this;
  };

  $.gfx.fn.rotateOut = function(options) {
    if (options == null) {
      options = {};
    }
    $(this).queueNext(function() {
      return $(this).transform({
        rotateY: 0
      }).fix();
    });
    $(this).animate({
      rotateY: '-180deg'
    }, options);
    if (options.reset !== false) {
      $(this).queueNext(function() {
        return $(this).transform({
          rotateY: 0,
          display: 'none'
        }).unfix();
      });
    }
    return this;
  };

  $.gfx.fn.rotateIn = function(options) {
    if (options == null) {
      options = {};
    }
    $(this).queueNext(function() {
      return $(this).transform({
        rotateY: '180deg',
        display: 'block'
      }).fix();
    });
    $(this).animate({
      rotateY: 0
    }, options);
    $(this).queueNext(function() {
      return $(this).unfix();
    });
    return $ = jQuery;
  };

  $.gfx.fn.slideOut = function(options) {
    var distance, opacity;

    if (options == null) {
      options = {};
    }
    options.direction || (options.direction = 'right');
    distance = options.distance || 100;
    if (options.direction === 'left') {
      distance *= -1;
    }
    distance += "%";
    opacity = options.fade ? 0 : 1;
    $(this).queueNext(function() {
      return $(this).show();
    });
    $(this).animate({
      translate3d: "" + distance + ",0,0",
      opacity: opacity
    }, options);
    return $(this).queueNext(function() {
      return $(this).transform({
        translate3d: "0,0,0",
        opacity: 1
      }).hide();
    });
  };

  $.gfx.fn.slideIn = function(options) {
    var distance, opacity;

    if (options == null) {
      options = {};
    }
    options.direction || (options.direction = 'right');
    distance = options.distance || 100;
    if (options.direction === 'left') {
      distance *= -1;
    }
    distance += "%";
    opacity = options.fade ? 0 : 1;
    $(this).queueNext(function() {
      return $(this).transform({
        translate3d: "" + distance + ",0,0",
        opacity: opacity
      }).show();
    });
    return $(this).animate({
      translate3d: "0,0,0",
      opacity: 1
    }, options);
  };

  $.gfx.fn.raisedIn = function(options) {
    if (options == null) {
      options = {};
    }
    $(this).queueNext(function() {
      return $(this).transform({
        scale: '1',
        opacity: '0',
        translate3d: '0,-15px,0'
      }).show();
    });
    return $(this).animate({
      scale: '1',
      opacity: '1',
      translate3d: '0,0,0'
    }, options);
  };

  $.gfx.fn.raisedOut = function(options) {
    if (options == null) {
      options = {};
    }
    $(this).queueNext(function() {
      return $(this).transform({
        scale: '1',
        opacity: '1',
        translate3d: '0,0,0'
      });
    });
    $(this).animate({
      scale: '1',
      opacity: '0',
      translate3d: '0,-8px,0'
    }, options);
    return $(this).queueNext(function() {
      return $(this).hide().transform({
        scale: '1',
        opacity: '1',
        translate3d: '0,0,0'
      });
    });
  };

  $.gfx.fn.fix = function() {
    return $(this).each(function() {
      var $element, parentOffset, styles;

      $element = $(this);
      styles = $element.offset();
      parentOffset = $element.parent().offset();
      styles.left -= parentOffset.left;
      styles.top -= parentOffset.top;
      styles.position = 'absolute';
      return $element.css(styles);
    });
  };

  $.gfx.fn.unfix = function() {
    return $(this).each(function() {
      var element;

      element = $(this);
      return element.css({
        position: '',
        top: '',
        left: ''
      });
    });
  };

}).call(this);
